---
title: "Exploration_2"
author: "Sean"
date: "2/22/2022"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
### Set Environment ------------------------------------------------------------
# Clear the environment
rm(list=ls())
gc()
# So the code will compile warnings as per usual
options(warn = 0)
# Turn off scientific notation
options(scipen = 999)
### Load Packages --------------------------------------------------------------
if(!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, magrittr, stringr, reshape2, janitor,
lubridate, readxl, data.table, ggplot2, scales, readr,
tidyr, zoo, skimr, openxlsx,ggspatial, rgeos, data.table,RColorBrewer,
tidyverse, rio, collapse, sf, glue, XML, tm, here, purrr, repurrrsive,
tmap,tidygraph, nabor,igraph, viridis, hrbrthemes,RSocrata,soql,xts,
tidycensus)
```
```{r}
dataset_id <- "erm2-nwe9"
api_endpoint <- paste0('https://data.cityofnewyork.us/resource/', dataset_id, '.json')
api_token <- "YRWk8RdZZ9xPMVbxc0QaHgYFU"
```

```{r}
DEP_Query <- read_rds("../3_Intermediate/DEP_Data.rds")
```

#### Declare functions
```{r}
# Function for filtering complaints depending on what years and complaints we will 
# later want to visualize
complaint_filter <- function(complaints,complaint_types,level,years){
  filtered <- complaints %>%  
    st_drop_geometry %>% 
    filter(complaint_type %in% complaint_types,
           year %in% years) %>% 
    group_by(ct2010, boro_name) %>% 
    summarise(n = sum(n))
  return(filtered)
}

# Function for creating choropleth maps depending on the filtered data
complaint_mapping <- function(shapefile,filtered,output_type,years,complaints){
  
  if(length(complaints) == length(c("Air Quality","Lead","Water Conservation","Industrial Waste",
                "Sewer","Water System","Asbestos","Hazardous Materials"))){
    complaints = "All Complaints"
  } else {
    complaints = glue_collapse(complaints,", ")
  }
    ct <- shapefile %>% 
      left_join(filtered,by= c("ct2010","boro_name")) 
    map <- tm_shape(ct) +
      tm_fill("n",title="Complaints",style="jenks", palette = "viridis", lwd = .01) +
      tm_layout(main.title = paste0("NYC Complaints from \n",complaints),
                main.title.position = "center",
                main.title.size = 1,
                main.title.fontface = 2
      )
    if(output_type == "map"){
      return(map)
    }
    else if(output_type == "shape"){
      return(ct)
    }
       
    
  }
```

```{r}

# read shapefiles for census tract (New York Long Island CRS)
ct <- st_read("../2_Data/ct_2010/geo_export_1c19ce5f-d77c-4a3f-adbe-7456e4a782a6.shp") %>% 
    st_transform(crs = 2263) %>% 
    mutate(unique = paste0(boro_name,ct2010)) 

# Turn Query into SF object with points. 
# We can use this later if we need to redo it, otherwise save it for faster processing.

# DEP_points <- DEP_Query %>% 
#   filter(complaint_type %in% complaints) %>%
#   select(c("unique_key",
#            "complaint_type",
#            "created_date",
#            "x_coordinate_state_plane",
#            "y_coordinate_state_plane")) %>% 
#   drop_na() %>% 
#   st_as_sf(coords = c("x_coordinate_state_plane","y_coordinate_state_plane"),
#            crs = 2263) %>% 
#   mutate(year = year(created_date)) 
# 
# saveRDS(DEP_points,"../3_Intermediate/DEP_points.rds")

## We can use a smaller test sample size to see if our visualization is working:

DEP_points <- read_rds("../3_Intermediate/DEP_points.rds")

```


```{r}


## For Querying:
all_params <- soql() %>%
    soql_add_endpoint(api_endpoint) %>% 
    soql_where("created_date between '2019-01-01T00:00:00.000' and '2020-01-01T00:00:00.000'") %>% 
    soql_select("unique_key, created_date, agency_name, complaint_type, descriptor, x_coordinate_state_plane,y_coordinate_state_plane") 

# where=date_occ between '2015-01-10' and '2015-12-13'

Query_311 <- read.socrata(
  all_params,
  app_token = api_token
)
  
saveRDS(Query_311,"Query_311.rds")

# Turn Query into SF object with points.
# We can use this later if we need to redo it, otherwise save it for faster processing.

Query_points <- Query_311 %>% 
  select(c("unique_key",
           "complaint_type",
           "created_date",
           "x_coordinate_state_plane",
           "y_coordinate_state_plane")) %>%
  drop_na() %>%
  st_as_sf(coords = c("x_coordinate_state_plane","y_coordinate_state_plane"),
           crs = 2263) %>%
  mutate(year = year(created_date))

saveRDS(Query_points,"../3_Intermediate/Query_points.rds")

ct_complaints_all_311 <- ct %>%
  st_intersection(Query_points) %>%
  group_by(ct2010,boro_name,complaint_type,year) %>%
  count()

saveRDS(ct_complaints_all_311,"../3_Intermediate/ct_complaints_all_agencies.rds")

```


```{r}
## Adjust inputs if needed:

years = c(2019)
## Mapping 3 times, we need 3 datasets for ct and cb 
ct_complaints_all <- read_rds("../3_Intermediate/ct_complaints_all.rds")
ct_complaints_all_311 <- read_rds("../3_Intermediate/ct_complaints_all_agencies.rds")

map_ct_complaints <- rep(list(ct_complaints_all),3) 

## Map over the complaints 3 times
map_complaints <- c("Air Quality","Sewer","Water System")

air_quality<- complaint_filter(ct_complaints_all,"Air Quality","shape",2019)
sewer <- complaint_filter(ct_complaints_all,"Sewer","shape",2019)
water_system<- complaint_filter(ct_complaints_all,"Water System","shape",2019)

All_by_CT <- ct_complaints_all_311 %>% 
    group_by(ct2010,boro_name) %>% 
    summarise(n = sum(n)) %>% 
    left_join(air_quality, by = c("ct2010","boro_name"),suffix = c("_original","_aq")) %>% 
    left_join(sewer, by = c("ct2010","boro_name"),suffix = c("_aq","_sewer")) %>% 
    left_join(water_system, by = c("ct2010","boro_name"),suffix = c("_sewer","_ws")) %>% 
    mutate(aq_prop = n_aq/n_original,
           sewer_prop = n_sewer/n_original,
           water_prop = n_ws/n_original) %>% 
    st_drop_geometry()
```


```{r}


All_by_CT_plot <- ct %>% 
    left_join(All_by_CT, by = c("ct2010","boro_name"))

air_quality_all <- tm_shape(All_by_CT_plot) +
    tm_fill("aq_prop",title="Complaints",style="jenks", palette = "viridis", lwd = .01,n =10) +
    tm_layout(main.title = paste0("NYC Complaints from Air Quality"),
              main.title.position = "center",
              main.title.size = 1,
              main.title.fontface = 2) 

tmap_save(air_quality_all,"../4_Outputs/Air_Quality_prop_all_jenks.png")
  
sewer_all <- tm_shape(All_by_CT_plot) +
    tm_fill("sewer_prop",title="Complaints",style="jenks", palette = "viridis", lwd = .01,n =10) +
    tm_layout(main.title = paste0("NYC Complaints from Sewers"),
              main.title.position = "center",
              main.title.size = 1,
              main.title.fontface = 2)

tmap_save(sewer_all,"../4_Outputs/sewer_prop_all_jenks.png")



water_all <- tm_shape(All_by_CT_plot) +
    tm_fill("water_prop",title="Complaints",style="jenks", palette = "viridis", lwd = .01,n =10) +
    tm_layout(main.title = paste0("NYC Complaints from Water System"),
              main.title.position = "center",
              main.title.size = 1,
              main.title.fontface = 2)

tmap_save(water_all,"../4_Outputs/water_prop_all_jenks.png")

```

```{r}
census_api_key("4878f9292ac0c11cddc6fabc8cd8530c4d0e12f0")

v2019 <- load_variables(2019, "acs5", cache = TRUE)

demographics <- v2019 %>% 
  filter(grepl("B02001",name))

demographics <- c(white = "B02001_002",
                  total = "B02001_001",
                  income ="B19113_001",
                  language_bad = "B16004_045",
                  language_not_well = "B16004_044",
                  native_born = "B05002_002")
Census_2019 <- 
  get_acs(
    state = 36, 
    county = c("061", "047", "081", "005", "085"), 
    geography = "tract", 
    variables = demographics,
    year = 2019
  ) %>% 
  transmute(
    cnty = str_sub(GEOID, 3, 5),
    tract = as.integer(str_sub(GEOID, 6, 12)), 
    measure = estimate, 
    boro_name = 
      case_when(
        cnty == "061" ~ "Manhattan", 
        cnty == "047" ~ "Brooklyn", 
        cnty == "081" ~ "Queens", 
        cnty == "005" ~ "Bronx", 
        cnty == "085" ~ "Staten Island"
      ), 
    ctlabel = as.character(tract / 100),
    variable = variable)

Population_2019 <- Census_2019 %>% 
  filter(variable == 'total')

census_shapes <- ct %>% 
    left_join(Population_2019, by = c("boro_name", "ctlabel"))

```
```{r}
## Mapping 8 times, we need 8 datasets for ct and cb 
map_ct_complaints <- rep(list(ct_complaints_all),3) 

## Map over the complaints 8 times
map_complaints <- c("Air Quality",
                "Sewer","Water System")

## Input "map" 8 times
map_ct <- rep("shape",3)

## For now, put in all years, 8 times.          
map_years <- rep(list(years),3)

## Prepare inputs for filtering
input_ct <- list(map_ct_complaints,map_complaints,map_ct,map_years)

## Filter ct inputs.
filtered_ct_all <- pmap(input_ct,complaint_filter)

popjoin <- function(ct,pops){
  census_shapes <- ct %>% 
    left_join(pops, by = c("boro_name", "ctlabel")) %>% 
    mutate(measure = na_if(measure,0),
           measure = na_if(measure,2),
           percapita = n/measure)
  return(census_shapes)
}
plotting_percapita <- function(ct,complaints){
  map <- tm_shape(ct) +
    tm_fill("percapita",title="Complaints",style="jenks", palette = "viridis", lwd = .01,n =10) +
    tm_layout(main.title = paste0("NYC Complaints from \n",complaints),
              main.title.position = "center",
              main.title.size = 1,
              main.title.fontface = 2)
  return(map)
}

shape_ct <- rep("shape",3)
map_ct_shapes <- rep(list(ct),3) 
map_years <- rep(list(years),3)
input_ct_shapes <- list(map_ct_shapes,filtered_ct_all, shape_ct,map_years,map_complaints)
map_pop <- rep(list(Population_2019),3)
shapes_ct_all <- pmap(input_ct_shapes,complaint_mapping)
join_pop_inputs <- list(shapes_ct_all,map_pop)
ct_totalpop <- pmap(join_pop_inputs,popjoin)

percapita_inputs <-list(ct_totalpop,map_complaints)
ct_percapita_all <- pmap(percapita_inputs,plotting_percapita)
ct_percapita_all

norm_plotnames = imap(map_complaints, ~paste0("../4_Outputs/",., "_perCapita_2019_jenks.png")) %>%
     flatten()

norm_plotnames

pwalk(list(ct_percapita_all,norm_plotnames), tmap_save)


```


```{r}

ct_complaints_all <- read_rds("../3_Intermediate/ct_complaints_all.rds")

complaints_air <- ct_complaints_all %>% 
    filter(complaint_type == "Air Quality") %>% 
    st_drop_geometry() %>% 
    group_by(ct2010, boro_name) %>% 
    summarise(n = sum(n)) 

ct_air_sf <- ct %>% 
    left_join(complaints_air, by = c("ct2010","boro_name")) %>% 
    filter(boro_name %in% c("Queens","Brooklyn")) %>% 
    left_join(Population_2019,by = c("boro_name", "ctlabel")) %>% 
    mutate(air_p_capita = n/measure)

transit <- st_read("../2_Data/built_env/New York City Truck Routes/geo_export_986e2c20-dde0-4633-af70-c1d21bc1e383.shp") %>% 
    st_transform(crs = 2263)

construction <- st_read(
    "../2_Data/built_env/Street and Highway Capital Reconstruction Projects - Block/geo_export_b32362d7-1202-4cef-86f6-8c75320f707a.shp") %>% 
    st_transform(crs = 2263) 

zoom_in <- tm_shape(ct_air_sf) +
      tm_fill("air_p_capita",title="Complaints",style="jenks", palette = "BuPu", lwd = .03) +
      tm_layout(main.title = "Air Quality",
                main.title.position = "center",
                main.title.size = 1,
                main.title.fontface = 2,
                legend.outside = TRUE
      ) +
    tm_shape(construction) +
    tm_lines(lwd = .5, alpha = .5, col = "red") + 
    tm_layout(legend.outside = TRUE) +
    tm_shape(transit)+
    tm_lines(lwd = .5, alpha = .5, col = "brown") +
    tm_layout(legend.outside = TRUE) 
zoom_in

tmap_save(zoom_in,"../4_Outputs/Air_Quality_Zoom.png")

```

